// <auto-generated />
namespace Uvv.TesteAgil.Dados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TADBMigracaoInicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TADBMigracaoInicial));
        
        string IMigrationMetadata.Id
        {
            get { return "201804012358521_TADB-Migracao-Inicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
